title = "TOML Example 3 Modified"

[[personas]]
name = "John Doe"
age = 30
city = "New York"

[[personas]]
name = "Jane Smith"
age = 25
city = "London"

[[books]]
title = "Book A"
author = "Author A"
year = 2022

[[books]]
title = "Book B"
author = "Author B"
year = 2021

[[cars]]
make = "Toyota"
model = "Camry"
year = 2020

[[cars]]
make = "Honda"
model = "Civic"
year = 2019
