# Configurações do servidor web

titulo = "Meu Servidor Web"
porta = 8080
ativo = true
diretorio_raiz = "/var/www/html"

# Configurações do banco de dados
[banco_de_dados]
host = "localhost"
porta = 5432
usuario = "usuario"
senha = "senha"
banco = "meu_banco_de_dados"

# Configurações de cache
[cache]
ativo = true
tipo = "redis"
host = "localhost"
porta = 6379